=== ivanmihajlov/papers_please/papers_please/papers_please/src/main/resources/xsd/evaluation_form.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/ivanmihajlov/papers_please/evaluation_form"
    xmlns="https://github.com/ivanmihajlov/papers_please/evaluation_form">
    <xs:element name="evaluation_form">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="reviewer"/>
                <xs:element name="scientific_paper_title">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="0"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="scientific_paper_summary">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="0"/>
                            <xs:maxLength value="400"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element ref="suggestions"/>
                <xs:element ref="overall_recommendation"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
            <xs:attribute name="reviewer_id" type="xs:date"/>
            <xs:attribute name="scientific_paper_id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="overall_recommendation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="recommendation">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Accept"/>
                            <xs:enumeration value="Minor Revision"/>
                            <xs:enumeration value="Major Revision"/>
                            <xs:enumeration value="Reject"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="recommendation_comment">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="0"/>
                            <xs:maxLength value="200"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="suggestions">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="suggestion"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="suggestion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ref" type="xs:string"> </xs:element>
                <xs:element name="comment">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="0"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="reviewer">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="TPerson">
                    <xs:sequence>
                        <xs:element name="email">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[\w-]+@([\w-]+\.)+[\w-]+"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TScore">
        <xs:sequence>
            <xs:element name="score">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="1"/>
                        <xs:maxInclusive value="5"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="comment" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPerson">
        <xs:sequence>
            <xs:element name="first_name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element minOccurs="0" name="middle_name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="last_name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ivanmihajlov/papers_please/papers_please/papers_please/src/main/resources/examples/evaluationFormExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<evaluation_form xmlns="https://github.com/ivanmihajlov/papers_please/evaluation_form"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/ivanmihajlov/papers_please file:/C:/Users/mihaj/Desktop/xsd/evaluation_form.xsd">
    <reviewer>
        <first_name>Iva</first_name>
        <last_name>Ivic</last_name>
        <email>ivaivic@gmail.com</email>
    </reviewer>
    <scientific_paper_title>Moon mining</scientific_paper_title>
    <scientific_paper_summary>Prospects of moon mining industry</scientific_paper_summary>
    <suggestions>
        <suggestion>
            <ref>Paper text</ref>
            <comment>My comment</comment>
        </suggestion>
    </suggestions>
    <overall_recommendation>
        <recommendation>Minor Revision</recommendation>
        <recommendation_comment>Correct issues</recommendation_comment>
    </overall_recommendation>
</evaluation_form>
