=== ivanmihajlov/papers_please/papers_please/papers_please/src/main/resources/xsd/scientific_paper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    targetNamespace="https://github.com/ivanmihajlov/papers_please"
    xmlns="https://github.com/ivanmihajlov/papers_please"
    xmlns:jxb="http://java.sun.com/xml/ns/jaxb" jxb:version="2.0"
    xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
    xmlns:pred="https://github.com/ivanmihajlov/papers_please/predicate/"
    xmlns:rdfa="http://www.w3.org/ns/rdfa#">

    <xs:annotation>
        <xs:appinfo>
            <jxb:serializable uid="1"/>
            <jxb:globalBindings>
                <jxb:javaType name="java.util.Date" xmlType="xs:date" parseMethod="com.ftn.scientific_papers.util.MyDatatypeConverter.parseDate" printMethod="com.ftn.scientific_papers.util.MyDatatypeConverter.printDate"/>
                
                <jxb:javaType name="java.util.Date" xmlType="xs:gYear" parseMethod="com.ftn.scientific_papers.util.MyDatatypeConverter.parseDate" printMethod="com.ftn.scientific_papers.util.MyDatatypeConverter.printDate"/>
                
            </jxb:globalBindings>
        </xs:appinfo>
    </xs:annotation>

    <xs:complexType name="TPerson">
        <xs:sequence>
            <xs:element name="first_name" minOccurs="1">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:anyAttribute namespace="http://www.w3.org/ns/rdfa#"
                                processContents="lax"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="middle_name" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="last_name">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:anyAttribute namespace="http://www.w3.org/ns/rdfa#"
                                processContents="lax"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:group name="simple_paragraph_elements">
        <xs:sequence>
            <xs:element minOccurs="0" name="b" type="TEmphasis"/>
            <xs:element minOccurs="0" name="i" type="TEmphasis"/>
            <xs:element minOccurs="0" name="u" type="TEmphasis"/>
            <xs:element minOccurs="0" ref="unordered_list"/>
            <xs:element minOccurs="0" ref="ordered_list"/>
            <xs:element minOccurs="0" ref="quote"/>
        </xs:sequence>
    </xs:group>
    <xs:complexType mixed="true" name="TSimpleParagraph">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded" minOccurs="1">
                <xs:group ref="simple_paragraph_elements"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="optional"/>
    </xs:complexType>
    <xs:complexType name="TComplexParagraph" mixed="true">
        <xs:sequence>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="image"/>
                <xs:element ref="table"/>
                <xs:group ref="simple_paragraph_elements"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="optional"/>
    </xs:complexType>
    <xs:complexType mixed="true" name="TEmphasis">
        <xs:choice maxOccurs="unbounded" minOccurs="1">
            <xs:element minOccurs="0" name="b" type="TEmphasis"/>
            <xs:element minOccurs="0" name="i" type="TEmphasis"/>
            <xs:element minOccurs="0" name="u" type="TEmphasis"/>
        </xs:choice>
    </xs:complexType>
    <xs:simpleType name="TItem">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:element name="scientific_paper">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="head">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="received_date" minOccurs="1">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:date">
                                            <xs:anyAttribute namespace="http://www.w3.org/ns/rdfa#"
                                                processContents="lax"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="revised_date" minOccurs="1">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:date">
                                            <xs:anyAttribute namespace="http://www.w3.org/ns/rdfa#"
                                                processContents="lax"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="accepted_date" minOccurs="1">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:date">
                                            <xs:anyAttribute namespace="http://www.w3.org/ns/rdfa#"
                                                processContents="lax"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="title" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="lang" type="xs:string"
                                                use="optional"/>
                                            <xs:anyAttribute namespace="http://www.w3.org/ns/rdfa#"
                                                processContents="lax"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" ref="author"/>
                            <xs:element name="keyword" maxOccurs="15">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:anyAttribute namespace="http://www.w3.org/ns/rdfa#"
                                                processContents="lax"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:anyAttribute namespace="http://www.w3.org/ns/rdfa#"
                            processContents="lax"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="body">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="abstract">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="paragraph"
                                            type="TSimpleParagraph"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" ref="chapter"/>
                            <xs:element name="references">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" ref="reference"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>

            <xs:attribute name="status" default="PENDING" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="REVIEWING"/>
                        <xs:enumeration value="ACCEPTED"/>
                        <xs:enumeration value="REJECTED"/>
                        <xs:enumeration value="REVISION"/>
                        <xs:enumeration value="PENDING"/>
                        <xs:enumeration value="WITHDRAWN"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute default="1" name="version" type="xs:positiveInteger"/>
            <xs:anyAttribute namespace="http://www.w3.org/ns/rdfa#" processContents="lax"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="affiliation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:anyAttribute namespace="http://www.w3.org/ns/rdfa#"
                                    processContents="lax"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="city" type="xs:string"/>
                <xs:element name="state" type="xs:string" minOccurs="0"/>
                <xs:element name="country" type="xs:string"/>
            </xs:sequence>
            <xs:anyAttribute namespace="http://www.w3.org/ns/rdfa#" processContents="lax"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="author">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="TPerson">
                    <xs:sequence>
                        <xs:element minOccurs="0" name="email">
                            <xs:simpleType>
                                <xs:restriction base="xs:string"/>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element ref="affiliation"/>
                    </xs:sequence>
                    <xs:anyAttribute namespace="http://www.w3.org/ns/rdfa#" processContents="lax"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="chapter">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="heading"/>
                <xs:element maxOccurs="unbounded" name="paragraph" type="TComplexParagraph"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="chapter"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="optional"/>
            <xs:attribute name="level" use="optional">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:maxInclusive value="5"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="image">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="optional"/>
            <xs:attribute name="src" type="xs:string" use="required"/>
            <xs:attribute name="width" type="xs:positiveInteger"/>
            <xs:attribute name="height" type="xs:positiveInteger"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="unordered_list">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="1">
                <xs:element name="item" type="TItem"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="optional"/>
            <xs:attribute name="style" default="circle">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="disc"/>
                        <xs:enumeration value="circle"/>
                        <xs:enumeration value="square"/>
                        <xs:enumeration value="none"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="ordered_list">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="item" type="TItem"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="optional"/>
            <xs:attribute name="type" default="1">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="1"/>
                        <xs:enumeration value="A"/>
                        <xs:enumeration value="a"/>
                        <xs:enumeration value="I"/>
                        <xs:enumeration value="i"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="tr" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="th" type="xs:string" maxOccurs="unbounded"/>
                            <xs:element name="td" type="xs:string" maxOccurs="unbounded"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="quote">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="source" type="xs:string"/>
                <xs:element name="text" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="heading" type="xs:string"/>
    <xs:element name="reference">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="paper_id" type="xs:string"/>
                <xs:element name="title" type="xs:string"/>
                <xs:element maxOccurs="unbounded" name="reference_author" type="TPerson"> </xs:element>
                <xs:element name="publisher" type="xs:string"/>
                <xs:element name="year_of_publication" type="xs:gYear"> </xs:element>
                <xs:element name="pages" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ivanmihajlov/papers_please/papers_please/papers_please/src/main/resources/examples/paperExample.xml
<?xml version="1.0" encoding="UTF-8"?>
<scientific_paper xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
 xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
 xmlns:pred="https://github.com/ivanmihajlov/papers_please/predicate/"
 xmlns:rdfa="http://www.w3.org/ns/rdfa#"
 xmlns="https://github.com/ivanmihajlov/papers_please"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/ivanmihajlov/papers_please file:/C:/Users/mihaj/Desktop/xsd/scientific_paper.xsd" id="ID001" status="PENDING" version="1">
    <head>
        <received_date>2020-09-05</received_date>
        <revised_date>2020-09-05</revised_date>
        <accepted_date>2020-09-05</accepted_date>
        <title lang="lang1">Moon mining</title>
        <title lang="lang3">Prospects of moon mining industry</title>
        <author>
            <first_name>Mare</first_name>
            <middle_name>M</middle_name>
            <last_name>Maric</last_name>
            <email>mare.maric@gmail.com</email>
            <affiliation>
                <name>Faculty of Technical Sciences</name>
                <city>Novi Sad</city>
                <state>Vojvodina</state>
                <country>Serbia</country>
            </affiliation>
        </author>
        <author>
            <first_name>Mika</first_name>
            <middle_name>M</middle_name>
            <last_name>Mikic</last_name>
            <email>mika.mikic@gmail.com</email>
            <affiliation>
                <name>Faculty of Technical Sciences</name>
                <city>Novi Sad</city>
                <state>Vojvodina</state>
                <country>Serbia</country>
            </affiliation>
        </author>
        <keyword>moon</keyword>
        <keyword>mining</keyword>
        <keyword>industry</keyword>
        <keyword>space</keyword>
    </head>
    <body>
        <abstract id="ID003">
            <paragraph id="ID005">
                paragraph1
                <quote id="ID011">
                    <source>paper0</source>
                    <text>Quoted text</text>
                </quote>
            </paragraph>
            <paragraph id="ID019">
                paragraph2
            </paragraph>
        </abstract>
        <chapter id="ID033" level="3">
            <heading>heading0</heading>
            <paragraph id="ID035">
                paragraph3
            </paragraph>
            <paragraph id="ID045">
                paragraph4
            </paragraph>
        </chapter>
        <chapter id="ID051" level="3">
            <heading>heading1</heading>
            <paragraph id="ID053">
                paragraph5
            </paragraph>
            <paragraph id="ID059">
                paragraph6
            </paragraph>
        </chapter>
        <references>
            <reference>
                <paper_id>paper0</paper_id>
                <title>Moon mining</title>
                <reference_author>
                    <first_name>Mare</first_name>
                    <middle_name>M</middle_name>
                    <last_name>Maric</last_name>
                </reference_author>
                <reference_author>
                    <first_name>Mika</first_name>
                    <middle_name>M</middle_name>
                    <last_name>Mikic</last_name>
                </reference_author>
                <publisher>Papers, please!</publisher>
                <year_of_publication>2020</year_of_publication>
                <pages>Page 43</pages>
            </reference>
        </references>
    </body>
</scientific_paper>
